### PR TITLE
[Kongou backports] Various improvements, /reload command

### PR DESCRIPTION
**Pull request by HerrCraziDev**
This introduces minor changes, all aimed at easing the development process, and the ability to reload "in place" Kongou's commands. 

**Changelog**
- Added `.vscode` and `package-lock.json` to `.gitignore` (the latter have been untracked)
- Added an `uid` field to `KongouInteractions` 
- Added a `/reload` command to reload the list of commands without interrupting the bot, which is only accessible to the owner and intended for dev uses. It could be made to admins if verified to be stable enough (which should be the case).
- Notifications will now be shown once for songs on "repeat one" or playlists on "repeat all" with only one song.

### CODE REVIEW

**Comment by Deivu** [comment]
Thanks for the PR, I assume this is tested and doesn't need any tests on my side?

**Comment by HerrCraziDev** [comment]
> Thanks for the PR, I assume this is tested and doesn't need any tests on my side?

Aloha ! Yeah, I ran it on my own, I have an instance of Kongou running. There's one case I noted where it would crash, and that's if you `/reload` commands with syntax errors and the `require()` fails, however in such a case the bot would have crashed on startup anyways. I'm aiming to fix this soon, but I haven't had much time these days.

**Comment by HerrCraziDev** [comment]
Should be fully stable now :rocket:

**Comment by Deivu** [comment]
Ok thanks for fixing that issue, I do agree that `syntax errors and the require() fails` must be fixed, due to the fact that the newer devs without a linter are more prone for that so we must ensure at least the bot won't crash

**Pull request merged**
